stages:
  - build
  - production

image: docker:git
services:
  - docker:dind

build_images_for_k8s:
  stage: build
  only:
    - master
  script:
    -  ./build/run-build
  tags:
    - docker

deploy_prod_k8s:
  stage: production
  image: lwolf/helm-kubectl-docker:latest
  only:
    - master
  script:
    - ./build/run-k8s
  tags:
    - docker
