module:
  garbage:
    name: Мусор
    description: Чего только не встретишь на свалке
    limit: 10

  hammer:
    name: Молот
    damage: 5
    energyCoast: 4
    limit: 20
    slots:
      - hand_l
      - hand_r
  knife:
    name: Нож
    description: Наносит удар сквозь щит
    damage: 1
    energyCoast: 2
    limit: 20
    slots:
      - hand_l
      - hand_r

  strengthening:
    name: Укрепление
    description: Пассивно увеличивает здоровье на 2
    healthBonus: 2
    limit: 2
    slots:
      - core
    passive: true
  energycell:
    name: Энергоячейка
    description: Пассивно увеличивает энергию на 4
    energyBonus: 4
    limit: 20
    slots:
      - core
    passive: true

robots:
  user:
    baseEnergy: 7
    baseHealth: 5
  core:
    baseEnergy: 9
    baseHealth: 7

available_slots:
  - head
  - hand_l
  - hand_r
  - core
  - foot
  - air

general:
  arming_rounds: 10
  core_slots_with_arming_rounds:
    1: 3
    2: 3
    3: 3
    4: 4
    5: 5
    6: 6
    7: 7
    8: 7
    9: 7
    10: 7
  core_use_energy_on_modules_in_percents:
    min: 50
    max: 75
