module:
  garbage:
    name: мусор
    description: чего только не встретишь на свалке
    limit: 4


  laser:
    name: лазер
    description: наносит урон
    damage: 1
    energyCoast: 2
    limit: 3
    slots:
      - head
  aim:
    name: прицел
    description: увеличивает на 1 первую атаку по врагу
    energyCoast: 3
    limit: 3
    slots:
      - head
  barrier:
    name: барьер
    description: увеличивает оставшуюся после активации модулей энергию в 2 раза
    energyCoast: 3
    limit: 3
    slots:
      - head
  sonicboom:
    name: звуковой удар
    description: увеличивает цену активации модулей врага на 1 на следующий ход
    energyCoast: 3
    limit: 3
    slots:
      - head


  hammer:
    name: молот
    damage: 5
    energyCoast: 4
    limit: 3
    slots:
      - hand_l
      - hand_r
  knife:
    name: нож
    description: наносит удар сквозь щит
    damage: 1
    energyCoast: 2
    limit: 3
    slots:
      - hand_l
      - hand_r
  flamethrower:
    name: огнемёт
    description: наносит периодический урон (3 хода)
    damage: 1
    energyCoast: 3
    limit: 3
    slots:
      - hand_l
      - hand_r
  capture:
    name: захват
    description: блок случайного вражеского модуля
    damage: 1
    energyCoast: 2
    limit: 3
    slots:
      - hand_l
      - hand_r
  shield:
    name: щит
    description: блок одной вражеской атаки
    energyCoast: 2
    limit: 2
    slots:
      - hand_l
      - hand_r
  rocket:
    name: ракета
    energyCoast: 3
    damage: 3
    limit: 2
    slots:
      - hand_l
      - hand_r
  saw:
    name: пила
    description: наносит 2 атаки
    energyCoast: 3
    damage: 2
    limit: 2
    slots:
      - hand_l
      - hand_r
  machinegun:
    name: пулемёт
    description: наносит 3 атаки
    energyCoast: 4
    damage: 1
    limit: 2
    slots:
      - hand_l
      - hand_r

  strengthening:
    name: укрепление
    description: пассивно увеличивает здоровье на 2
    healthBonus: 2
    limit: 3
    slots:
      - core
    passive: true
  energycell:
    name: энергоячейка
    description: пассивно увеличивает энергию на 4
    energyBonus: 4
    limit: 3
    slots:
      - core
    passive: true
  accelerator:
    name: акселератор
    description: игнорирование одной атаки
    energyCoast: 3
    limit: 2
    slots:
      - core


  maneuvering:
    name: маневрирование
    description: уклонение от одной вражеской атаки
    energyCoast: 3
    limit: 3
    slots:
      - foot
  attack:
    name: нападение
    description: урон следующей атаки удваивается
    energyCoast: 3
    limit: 1
    slots:
      - foot
  ram:
    name: таран
    description: наносит урон
    damage: 1
    energyCoast: 2
    limit: 3
    slots:
      - foot


robots:
  vk:
    baseEnergy: 7
    baseHealth: 5
  core:
    baseEnergy: 9
    baseHealth: 7

available_slots:
  - head
  - hand_l
  - hand_r
  - core
  - foot
  - air

general:
  arming_rounds: 10
  core_slots_with_arming_rounds:
    1: 3
    2: 3
    3: 3
    4: 4
    5: 5
    6: 6
    7: 7
    8: 7
    9: 7
    10: 7
  core_use_energy_on_modules_in_percents:
    min: 50
    max: 75
